### ISSUE TITLE
Question: How does this project has to do with lazy loading views?

### ISSUE THREAD

**Issue by zardilior** [teracyhq/flask-classful#103]
The question in the title

**Comment by hoatle** [comment]
@zardilior AFAIK, there is no lazy loading views.

**Comment by zardilior** [comment]
How could you go about it? Or it can't be implemented with this library?

**Comment by hoatle** [comment]
I have no idea how to use lazy loading views with flask-classful, it's not supported by this library AFAIK. I don't know if someone has a way to use lazy loading views with this library.

**Comment by zardilior** [comment]
So its not even contemplated in the future of this library? As lazy loading views is one of the principal scalability techniques to do in flask

**Comment by hoatle** [comment]
@zardilior in the future maybe someone could send a proposal/ docs/ examples/ PR for this use case.
