### ISSUE TITLE
@staticmethod

### ISSUE THREAD

**Issue by Psychokiller1888** [teracyhq/flask-classful#112]
Hello!

First things first, thanks for this, it's really enjoyable to use flask in an object orientated way!

Some of my views inherit from other classes, or some of my view's methods don't need self, thus should be declared with @staticmethod, but unfortunately when using this decorator, flask-classful is not happy at all and breaks:

```
Traceback (most recent call last):
  File "main.py", line 89, in <module>
    main()
  File "main.py", line 75, in main
    projectAlice = ProjectAlice()
  File "/home/pi/ProjectAlice/core/ProjectAlice.py", line 17, in __init__
    self._superManager.onStart()
  File "/home/pi/ProjectAlice/core/base/SuperManager.py", line 82, in onStart
    manager.onStart()
  File "/home/pi/ProjectAlice/core/interface/WebInterfaceManager.py", line 60, in onStart
    view.register(self.app)
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/flask_classful.py", line 193, in register
    .format(name, cls.__name__))
flask_classful.DecoratorCompatibilityError: Incompatible decorator detected on decorate in class AdminView
```

Anyway out of this?

**Comment by hoatle** [comment]
@Psychokiller1888 you can try `excluded_methods ` mentioned here http://flask-classful.teracy.org/#hiding-your-own-methods-they-re-not-all-special

**Comment by Psychokiller1888** [comment]
I'm not excluding methods, they are all used by the view.... The view itself inherits from classes that inherit from classes having some @staticmethod decorators and everything breaks

**Comment by hoatle** [comment]
@Psychokiller1888 I added this test for your case, it should work when you follow the same by using `excluded_methods ` https://github.com/hoatle/flask-classful/commit/11d458effe32944213d9075e6c4dedcd83e74696
