### ISSUE TITLE
3rd party decorator problems

### ISSUE THREAD

**Issue by incognick** [teracyhq/flask-classful#14]
I'm having issues with flask-apispec using flask-classful. The issue is that apispec attaches information to the decorated function. I tried to fix it within their code but it is very complicated.  

I fixed this in flask classful make_proxy_method to decorate the proxy rather than decorate the bound instance method. Anyone apposed to this fix?  I'll submit a PR to aid the discussion.

**Comment by hoatle** [comment]
@incognick could you create unit tests for the change? Especially for `decorators` for this: http://flask-classful.teracy.org/#decorating-tips

We're lacking the tests for `decorators` attribute of FlaskView

**Comment by incognick** [comment]
Sure @hoatle

**Comment by revmischa** [comment]
How does one use flask_classful with flask_apispec? I cannot figure out how to register FlaskViews.
