### ISSUE TITLE
Flask Classful endpoint fetch via React blocked by CORS policy

### ISSUE THREAD

**Issue by buckleytoby** [teracyhq/flask-classful#143]
`Access to fetch at 'http://localhost:5000/....' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

Having difficulty reading data into my React app. Adding response headers in the function isn't working either
```
response = flask.jsonify(out)
response.headers.add('Access-Control-Allow-Origin', '*')
return response
```

**Comment by dev-rijan** [comment]
If you want to enable CORS for all routes, you can install [Flask-cors](https://github.com/corydolphin/flask-cors) extension.
Note: if there is an error in your route, let us say you try to print a variable that does not exist, you will get a CORS related error message which, in fact, has nothing to do with CORS.

**Comment by buckleytoby** [comment]
I'm following this post: https://stackoverflow.com/a/33091782/2985406

I've already installed Flask-cors and tried it that way to with no success, unfortunately.
I believe the route works because if I click the url localhost:5000/.../... then the endpoint with data will load in my browser

**Comment by buckleytoby** [comment]
The problem was that I was missing a trailing `/` on my fetch request, and I had an unneeded trailing `/` on my `response.headers.add("Access-Control-Allow-Origin", "http://localhost:3000")`.

It works now.
