### ISSUE TITLE
route_base and trailing_slash conflict.

### ISSUE THREAD

**Issue by raizyr** [teracyhq/flask-classful#31]
If you use both `route_base = "/"`  and `trailing_slash = False`, you'll get the following:
```
ValueError: urls must start with a leading slash
```
See Pull Request #30

**Comment by hoatle** [comment]
@raizyr thank you very much, it's merged. I'm going to release v0.13.1 for this bug fix.

**Comment by hoatle** [comment]
v0.13.1 released, enjoy! https://pypi.python.org/pypi/Flask-Classful
