### ISSUE TITLE
Question on REST hierarchy 

### ISSUE THREAD

**Issue by j-walker23** [teracyhq/flask-classful#37]
Hey, we have been using flask-classful for a while now and it has been awesome.
Really appreciate you taking this repo over!

Anyway, my question has to deal with architecting views for models who are children.
When i started the architecture it was my first flask app and i couldn't find any help so i made up a lame strat. At the time I was still using flask-classy, hadn't yet figured out it was taken over, and there have been several things that i thought were impossible until i thankfully replaced classy with classful so i am wondering if this question is similar.

With the code below, is there any way to make views "smart" so they know about their parent's rest routes without the repetition in `route_prefix`. Now that i have 50+ models I would really like to be doing the better way for this architecture (if there is one), before i have 100+ models lol.

I have tried inheritance, and different combinations of `route_prefix` with `route_base` while following how they get built with the `classful` internals and i couldn't find a good strategy.

``` python
class ParentView(FlaskView):
  """View for Parent model"""
  route_prefix = '/api/v1/parent'

  def get(self, parent_id: int):
    pass


class ChildView(FlaskView):
  """View for Child model"""
  route_prefix = '/api/v1/parent/<int:parent_id>/child'

  def get(self, parent_id: int, child_id: int):
    pass


class GrandKidView(FlaskView):
  """View for GrandKid model"""
  route_prefix = '/api/v1/parent/<int:parent_id>/child/<int:child_id>/grandkids'

  def get(self, parent_id: int, child_id: int, grandkid_id: int):
    pass
```

As always thanks for any help!

**Comment by hoatle** [comment]
@j-walker23 thank you for your question, I'll look into this soon.

**Comment by hoatle** [comment]
@j-walker23 there is currently no way to specify parent/child relationship.

I'm thinking about this:

```
class ParentView(FlaskView):
    route_prefix = '/api/v1/parent'
    

class ChildView(FlaskView):
    parent = ParentView  # define default parent/child relationship for route_prefix (or other things later)
    route_prefix = '/<int:parent_id>/child'
    

class GrandKidView(FlaskView):
    route_prefix = '/<int:child_id>/grandkids'
    

ParentView.register(app)
ChildView.register(app) # use default parent attribute
GrandKidView.register(app, parent=ChildView)  # use parent attribute on usage phase (override)
```
  
What do you think about this?

**Comment by j-walker23** [comment]
That looks like exactly what i would be looking for! How would the dev load be?

**Comment by hoatle** [comment]
for the workload, we need:
- write unit tests for the changes
- implement it
I estimate that it could take me ~8 hours to get it done. It's great if you could help to get it done.

**Comment by j-walker23** [comment]
Sounds great. I am at the tail end of a long release so i'll plan to dig in this weekend. I'll reply then for some guidance.

Thanks!

**Comment by NsLib** [comment]
Does anyone working on this feature?
I met the same issue.

**Comment by hoatle** [comment]
As I can see, introducing parent attribute for View classes will mess things up and it's best practices that don't introduce too many REST hierarchy levels, it's REST APIs style best practices.

For the REST APIs above, I guess we can break it into 3 nouns:

```
/api/v1/parents/

/api/v1/children/

/api/v1/grand-kids/
```

=> we can create 3 view classes: 

```python
class ParentsView(FlaskView):

    def get(self, parent_id):
        pass


class ChildrenView(FlaskView):

    def get(self, child_id):
        pass


class GrandKidsView(FlaskView):

    def get(self, grandkid_id):
        pass
```

=> and the register the 3 view classes:

```python
ParentsView.register(app, route_prefix='/api/v1/')
ChildrenView.register(app, route_prefix='/api/v1/')
GrandKidsView.register(app, route_prefix='/api/v1/')
```

That's how we should do it, don't introduce anti-pattern of REST APIs and we should be good.

**Comment by hoatle** [comment]
I'm closing this issue and feel free to re-open if you need any help.
