### ISSUE TITLE
not routing methods on base views

### ISSUE THREAD

**Issue by mattbillenstein** [teracyhq/flask-classful#38]
Hi, I have a 'BaseView' that extends FlaskView -- I want methods on this class to be ignored like they are for FlaskView -- is there a preferable way to implement this?

**Comment by mattbillenstein** [comment]
Potentially:  https://github.com/mattbillenstein/flask-classful/commit/d526534c9f666d9b80726d0fb8db03aadf190f1c

**Comment by hoatle** [comment]
https://github.com/mattbillenstein/flask-classful/commit/d526534c9f666d9b80726d0fb8db03aadf190f1c looks good to me, I'll cherry-pick this, thank you.
