### ISSUE TITLE
View methods not working as expected (?)

### ISSUE THREAD

**Issue by tjboring** [teracyhq/flask-classful#39]
I'm working on a rest api for a book database and have factored out two views: authors and books. The problem I'm having is that a basic GET for either an author or a book (http://localhost:5000/api/v1/[authors, books]/) works fine, but I'm getting a 404 error if I want to get a specfic author or book (http://localhost:5000/api/v1/author/1/ ).

[What the client sees]
```
$ curl -i http://localhost:5000/api/v1/authors/1/
HTTP/1.0 404 NOT FOUND
Content-Type: text/html
Content-Length: 233
Server: Werkzeug/0.11.11 Python/2.7.11
Date: Sun, 20 Nov 2016 23:04:38 GMT

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>
```

[Response from api]
```
127.0.0.1 - - [20/Nov/2016 18:04:38] "GET /api/v1/authors/1/ HTTP/1.1" 404 -
```

Here's what the relevant code for the AuthorsView class looks like:
```
class AuthorsView(FlaskView):
    route_prefix = '/api/v1/'

    def get(self, author_id=None):
        if author_id:
            author = Author.query.filter_by(author_id=author_id).first()
        #    if not author:
        #        raise InvalidUsage(
        #            'Author with id of %i not found.' % id,
        #            status_code=404)
            resp = jsonify(author.to_dict())
            resp.status_code = 200
            return resp
        authors = [a.to_dict() for a in Author.query.all()]
        #if not authors:
        #    raise InvalidUsage(
        #        'Authors not found.' % id, status_code=404)
        resp = jsonify(authors)
        resp.status_code = 200
        return resp
```
Any ideas what's going on here?

**Comment by tjboring** [comment]
It looks like from reading the [test cases](https://github.com/teracyhq/flask-classful/blob/develop/test_classful/view_classes.py#L18) that my code should work. Am I doing something wrong with the `route_prefix`?

**Comment by hoatle** [comment]
@tjboring please try `route_prefix = '/api/v1/authors/'`

**Comment by hoatle** [comment]
@tjboring better try this instead:
- remove `route_prefix` from `AuthorsView`
- register the view with: `AuthorsView.register(app, route_prefix='/api/v1/')`

**Comment by tjboring** [comment]
I removed `route_prefix` from `AuthorsView` and added it to register call, but still same behavior. :(

**Comment by hoatle** [comment]
@tjboring I see the problem, it's not related to route.

It's actually related to the argument.

Change `def get(self, author_id=None):` to `def get(self, author_id):` and it should work.
