### ISSUE TITLE
Be able to provide arguments and a constructor

### ISSUE THREAD

**Issue by jsubirat** [teracyhq/flask-classful#40]
Hi,

First of all, many thanks for mantaining this project. I would like to know if this feature is currently supported. Imagine I have the following:

class ClassAView(FlaskView):
  def __init__(self, pagename):
       self.pagename = pagename

   def index():
        return 'Welcome to ' + self.pagename

Now, I would like to be able to instantiate an object of class ClassAView, register the Flask app to it, and give it a name as an argument to its constructor:

app = Flask(__name__)
instanceA = ClassAView('my page')
instanceA.register(app, route_base='/')
app.run()

I face some errors when doing something like this, so I tried to instantiate the object with an empty constructor, and then trying to define a setter method in order to provide "pagename". However, pagename is not stored and not displayed when requesting the index.

If not supported, I think it would be really nice to be able to interact with the REST facade with setter methods, or a constructor admitting arguments.

Many thanks for your help!

**Comment by hoatle** [comment]
@jsubirat sorry, your case is not supported as it's not the way how flask-classful works.
