### ISSUE TITLE
subdomains of the methods

### ISSUE THREAD

**Issue by SergeVL** [teracyhq/flask-classful#42]
It's not possible to register different methods in different subdomains due to next code in
FlaskView.register:

```
if not subdomain and sub:

      subdomain = sub

...

app.add_url_rule(rule, endpoint, proxy, subdomain=subdomain, **options)
````

**Comment by hoatle** [comment]
let me check on this soon

**Comment by hoatle** [comment]
hello @SergeVL, I don't think we should support subdomain config for specific methods, it's best practice to organize the same subdomain methods within a FlaskView and it should work.

You can check out the related tests here: https://github.com/teracyhq/flask-classful/blob/develop/test_classful/test_subdomains.py
