### ISSUE TITLE
working app example with flask-classful.

### ISSUE THREAD

**Issue by faststare** [teracyhq/flask-classful#45]
its hard to implement the post function without running app example.
why post function should required view function?  when I just have post with redirect in flask route decorator and work perfectly. please improve the documentation for flask newbie like. :(

**Comment by hoatle** [comment]
@faststare do you mean that you want to have redirect after a post function? Please check out the following snippet to see if it works for you.

```python
from flask import url_for, redirect
from flask_classful import FlaskView

class DuckyView(FlaskView):
    def index(self):
        return "Duckies!"

    def get(self, name):
        return "Duck %s" % name

    def post(self):
        return redirect(url_for("DuckyView:get", name="Howard"))
```

see more: http://flask-classful.teracy.org/#url-for-art-thou-romeo

**Comment by faststare** [comment]
I have link tag in index page that redirect for get/1. I'm trying to do is to post in the get page with form. Do I need other page for post method? but It seems you answer my questions. thanks hoatle

**Comment by faststare** [comment]
I could like to see an url_for('random') example. I spent 2 hours for it and nothing to improves.
It seems class based stuff based its not for me. :(

**Comment by faststare** [comment]
class DatabaseView(FlaskView):
	def index(self):
		files = FileBase.select_all()
		return render_template('db_connect.html', files=files)

	def update(self, id):
		return render_template('db_update.html')

	@route('/create', endpoint='create')
	def create(self):
		return render_template('db_create.html')

	def post(self):
		return redirect(url_for('DatabaseView:index'))


DatabaseView.register(app, route_base='db')

#views.py

{% extends 'pure/wtf.html' %}

{% block content %}
	<table>
		<thead>
			<tr>
				<td>File Name</td>
				<td>File Path</td>
				<td>Connection</td>
				<td>Edit</td>
			</tr>
		</thead>
		<tbody>
			{% if files %}
				{% for file in files %}
					<tr>
						<td>file.name</td>
						<td>file.file_path</td>
						<td><a href="url_for('DatabaseView:get', id='file.id')}"></a></td>
					</tr>
				{% endfor %}
			{% else %}
				<tr>
					<td colspan="4" style="color:red;">No Database has been created yet.</td>
				</tr>
			{% endif %}
		</tbody>
	</table>

	<a href="{{url_for('DatabaseView:update', id='1')}}">Testing</a>
	
{% endblock %}

# db_connect.html
#too much in the template. :(

**Comment by hoatle** [comment]
@faststare you should list the app.url_map to see:

```
app.url_mapMap([<Rule '/db/create' (HEAD, OPTIONS, GET) -> create>,
 <Rule '/db/' (HEAD, OPTIONS, GET) -> DatabaseView:index>,
 <Rule '/db/' (POST, OPTIONS) -> DatabaseView:post>,
 <Rule '/db/update/<id>' (HEAD, OPTIONS, GET) -> DatabaseView:update>,
 <Rule '/static/<filename>' (HEAD, OPTIONS, GET) -> static>])
```

by:
- using https://flask-script.readthedocs.io/en/latest/
- then:
```
$ python manage.py shell
>>> app.url_map
```

this will print all the url_map and I can see the problem with: `DatabaseView:create`
Basing on the url_map, it should be `create` endpoint instead, this is bad.

To fix, change `@route('/create', endpoint='create')` to `@route('/create')`

**Comment by faststare** [comment]
werkzeug.routing.BuildError: Could not build url for endpoint 'index'. Did you mean 'DatabaseView:index' instead?

I received this error when I uncomment out the <a> that link db_connect that have url_for(Database:create). I already change the route to @route('/create'). It don't understand the traceback error  while I just want to go db/create page from db/index. :(

**Comment by hoatle** [comment]
follow my instruction above to see the url map (with endpoints) and learn about Flask please.

**Comment by faststare** [comment]
ok. abandon flask-classful for now. it cost me more time than lessen it for just url routing. thanks hoatle
