### ISSUE TITLE
Breaking change re FlaskView.decorators missing in CHANGELOG (for v0.11.0)

### ISSUE THREAD

**Issue by wodow** [teracyhq/flask-classful#49]
https://github.com/teracyhq/flask-classful/commit/686be6ef6fd09d9c1719fa89763ad09baddf7fd0 changes the order in which decorators are applied, due to the introduction of `reversed()`.

This should be noted as a breaking change in the CHANGELOG?

**Comment by hoatle** [comment]
I missed this, I'll update the CHANGLOG accordingly, thank you for reporting this.

**Comment by wodow** [comment]
Thank you!
