### ISSUE TITLE
docs: type hint support could be mentioned more prominently

### ISSUE THREAD

**Issue by anowlcalledjosh** [teracyhq/flask-classful#82]
(spoiler: this is already a feature, I just didn't read far enough into the docs)

---

From the docs:

> ### Note
> 
> One important thing to note, is that `FlaskView` does not type your parameters, so if you want or need them you’ll need to define the route yourself using the `@route` decorator.

It would be very neat to be able to do something like

```python
class AnotherView(FlaskView):
    route_base = "home"

    def this_view(self, arg1: int, arg2: str):
        return "Args: %s, %s" % (arg1, arg2,)
```

and end up with a route like `/home/this_view/<int:arg1>/<string:arg2>` automatically, without having to do the `@route` decorator by hand.

#### Possible problems

Flask understands these types ("converters"):

- `string`: accepts any text without a slash (the default)
- `int`: accepts integers
- `float`: like int but for floating point values
- `path`: like the default but also accepts slashes
- `any`: matches one of the items provided
- `uuid`: accepts UUID strings

Of these, `int` and `float` will work as-is as Python type hints, `str` can be interpreted as `string`, and `typing.Any` as `any`.

The correct hint for `path` and `uuid` probably depends on what Flask passes them as – if Flask just passes them both as strings, then defining something like `flask_classful.path` and `flask_classful.uuid` (using `typing.NewType`) to be used as type hints is probably the best approach. OTOH, if Flask actually passes a `uuid.UUID` and/or `pathlib.Path`/`os.PathLike`, then it might be better to use those?

**Comment by anowlcalledjosh** [comment]
Hah, just read some more of the documentation and [this is already a feature](http://flask-classful.teracy.org/#type-hints-support-for-python-3)!

I guess this can be an "update the documentation" bug then :)

**Comment by hoatle** [comment]
@anowlcalledjosh it's great if you could suggest any changes by a pull request for this.

**Comment by hoatle** [comment]
Docs updated
