### ISSUE TITLE
adding __init__ method to classes created

### ISSUE THREAD

**Issue by Quintonssebaggala** [teracyhq/flask-classful#84]
how can i achieve something like this
`class MyBaseView(FlaskView):
    def __init__(self, model):
        self.model = model`
cos i get error TypeError: __init__() missing 1 required positional argument: 'model'
after registering and running my app

**Comment by jpyams** [comment]
Why would you want to do this?  If you want to access `model` from the calls, just define it in the module:

    model = SomeModel()

    class MyBaseView(FlaskView):

        def get(self):
            return model.getSomething()

**Comment by hoatle** [comment]
__init__ with addition arguments is not supported, closed.

**Comment by hoatle** [comment]
actually, init_argument is supported by the next release https://github.com/teracyhq/flask-classful/commit/72fd7dc2ea8ab2f601964d2c4bceb4d0f3ae7354#diff-7b0676c367589a150608f74924bf70d7
