### ISSUE TITLE
decorators that returns a value and flask classful

### ISSUE THREAD

**Issue by reem-codes** [teracyhq/flask-classful#88]
Hello

is there a way to support this?

I have the following class that uses customized decorators token_req and webargs's use_kwargs:

```
class AdView(FlaskView): 

    @token_req
    @use_kwargs(ad_schema.fields)
    def post(self, current_user, kwargs):
        print(**kwargs)
        return construct.post(model=Ad, schema=ad_schema, data=kwargs, current_user=current_user)
```

The route I want is `/ad` and the method is post, but because `token_req` returns the current user and `use_kwargs` returns the data entered, the url keeps showing 404 UNLESS I entered another two values like this:
`/ads/3/fg`. So how to support such a system?

**Comment by EvaSDK** [comment]
You could inject this data in either `request`, `session` or `g`. See http://flask.pocoo.org/docs/1.0/api/#flask.g and http://flask.pocoo.org/docs/1.0/api/#sessions for details.

**Comment by hoatle** [comment]
@reem-codes make sure the  `@token_req` should pass the current_user as another positional argument (follow this example decorator https://github.com/marshmallow-code/webargs/blob/dev/webargs/core.py#L450)

and the method should be defined as:

```
class AdView(FlaskView): 

    @token_req
    @use_kwargs(ad_schema.fields)
    def post(self, current_user, **kwargs):
        print(kwargs)
```
