### ISSUE TITLE
Internationalization with flask-classful

### ISSUE THREAD

**Issue by darkcircle** [teracyhq/flask-classful#89]
I'm about to apply i18n into flask-classful-based project,
but I still didn't find the way of using Flask-babel with flask-classful.

how can i do this? does i18n feature can work with flask-classful?

**Comment by hoatle** [comment]
hello @darkcircle, AFAIK, flask-classful should work well with Flask-Babel.

Sorry that I did not have any example project using flask-classful and Flask-Babel to show you how to do this.
