### ISSUE TITLE
inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()

### ISSUE THREAD

**Issue by krassowski** [teracyhq/flask-classful#94]
Hi @hoatle, thank you for maintaining flask-classful!

After migration to Python3.7 I am being flooded with deprecation warning - could you have a look at it?

```python3
virtualenv/python3.7.1/lib/python3.7/site-packages/flask_classful.py:382: DeprecationWarning:
inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
```

It might be that simple swapping of the order of this try-except would fix it:
https://github.com/teracyhq/flask-classful/blob/42fa5fce1fa97b1f00813b4ce0dd13ebebdb28cc/flask_classful.py#L446-L449

**Comment by hoatle** [comment]
thank you @krassowski, this will be fixed by the next release.
